// Generated by gencpp from file abb2400_sim/move_req.msg
// DO NOT EDIT!


#ifndef ABB2400_SIM_MESSAGE_MOVE_REQ_H
#define ABB2400_SIM_MESSAGE_MOVE_REQ_H

#include <ros/service_traits.h>


#include <abb2400_sim/move_reqRequest.h>
#include <abb2400_sim/move_reqResponse.h>


namespace abb2400_sim
{

struct move_req
{

typedef move_reqRequest Request;
typedef move_reqResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move_req
} // namespace abb2400_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb2400_sim::move_req > {
  static const char* value()
  {
    return "41e6e6b8cea8da564de4882c75f56b84";
  }

  static const char* value(const ::abb2400_sim::move_req&) { return value(); }
};

template<>
struct DataType< ::abb2400_sim::move_req > {
  static const char* value()
  {
    return "abb2400_sim/move_req";
  }

  static const char* value(const ::abb2400_sim::move_req&) { return value(); }
};


// service_traits::MD5Sum< ::abb2400_sim::move_reqRequest> should match
// service_traits::MD5Sum< ::abb2400_sim::move_req >
template<>
struct MD5Sum< ::abb2400_sim::move_reqRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb2400_sim::move_req >::value();
  }
  static const char* value(const ::abb2400_sim::move_reqRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb2400_sim::move_reqRequest> should match
// service_traits::DataType< ::abb2400_sim::move_req >
template<>
struct DataType< ::abb2400_sim::move_reqRequest>
{
  static const char* value()
  {
    return DataType< ::abb2400_sim::move_req >::value();
  }
  static const char* value(const ::abb2400_sim::move_reqRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb2400_sim::move_reqResponse> should match
// service_traits::MD5Sum< ::abb2400_sim::move_req >
template<>
struct MD5Sum< ::abb2400_sim::move_reqResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb2400_sim::move_req >::value();
  }
  static const char* value(const ::abb2400_sim::move_reqResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb2400_sim::move_reqResponse> should match
// service_traits::DataType< ::abb2400_sim::move_req >
template<>
struct DataType< ::abb2400_sim::move_reqResponse>
{
  static const char* value()
  {
    return DataType< ::abb2400_sim::move_req >::value();
  }
  static const char* value(const ::abb2400_sim::move_reqResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB2400_SIM_MESSAGE_MOVE_REQ_H
