// Generated by gencpp from file testing_msgs/OperatorSpeed.msg
// DO NOT EDIT!


#ifndef TESTING_MSGS_MESSAGE_OPERATORSPEED_H
#define TESTING_MSGS_MESSAGE_OPERATORSPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace testing_msgs
{
template <class ContainerAllocator>
struct OperatorSpeed_
{
  typedef OperatorSpeed_<ContainerAllocator> Type;

  OperatorSpeed_()
    : header()
    , humanSpeed(0.0)
    , robotVelocity(0.0)  {
    }
  OperatorSpeed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , humanSpeed(0.0)
    , robotVelocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _humanSpeed_type;
  _humanSpeed_type humanSpeed;

   typedef double _robotVelocity_type;
  _robotVelocity_type robotVelocity;





  typedef boost::shared_ptr< ::testing_msgs::OperatorSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::testing_msgs::OperatorSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct OperatorSpeed_

typedef ::testing_msgs::OperatorSpeed_<std::allocator<void> > OperatorSpeed;

typedef boost::shared_ptr< ::testing_msgs::OperatorSpeed > OperatorSpeedPtr;
typedef boost::shared_ptr< ::testing_msgs::OperatorSpeed const> OperatorSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::testing_msgs::OperatorSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::testing_msgs::OperatorSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::testing_msgs::OperatorSpeed_<ContainerAllocator1> & lhs, const ::testing_msgs::OperatorSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.humanSpeed == rhs.humanSpeed &&
    lhs.robotVelocity == rhs.robotVelocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::testing_msgs::OperatorSpeed_<ContainerAllocator1> & lhs, const ::testing_msgs::OperatorSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace testing_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::testing_msgs::OperatorSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::testing_msgs::OperatorSpeed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testing_msgs::OperatorSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testing_msgs::OperatorSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testing_msgs::OperatorSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testing_msgs::OperatorSpeed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::testing_msgs::OperatorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5cb69c02c631c93ca058b4ec5827b97";
  }

  static const char* value(const ::testing_msgs::OperatorSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5cb69c02c631c93ULL;
  static const uint64_t static_value2 = 0xca058b4ec5827b97ULL;
};

template<class ContainerAllocator>
struct DataType< ::testing_msgs::OperatorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "testing_msgs/OperatorSpeed";
  }

  static const char* value(const ::testing_msgs::OperatorSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::testing_msgs::OperatorSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 humanSpeed\n"
"float64 robotVelocity\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::testing_msgs::OperatorSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::testing_msgs::OperatorSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.humanSpeed);
      stream.next(m.robotVelocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OperatorSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::testing_msgs::OperatorSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::testing_msgs::OperatorSpeed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "humanSpeed: ";
    Printer<double>::stream(s, indent + "  ", v.humanSpeed);
    s << indent << "robotVelocity: ";
    Printer<double>::stream(s, indent + "  ", v.robotVelocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESTING_MSGS_MESSAGE_OPERATORSPEED_H
